/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void timer1_Action1(GTimer source) { //_CODE_:tmr:303382:
  //println("tmr - GTimer >> an event occured @ " + millis());
  changeMarkovState();
} //_CODE_:tmr:303382:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  surface.setTitle("Sketch Window");
  tmr = new GTimer(this, this, "timer1_Action1", 1000);
}

// Variable declarations 
// autogenerated do not edit
GTimer tmr; 